### ISSUE TITLE
AdvancedVideoView: crash on Android

### ISSUE THREAD

**Issue by Tronix117** [triniwiz/nativescript-videorecorder#40]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
I have two different crashes everytime I try to load a AdvancedVideoView. Working smoothly on iOS, but crash on Android, with a different crash weither I set `cameraPosition` to `back` or `front`.

### Which platform(s) does your issue occur on?
- Android
- tested on Nougat
- emulator (camera working great in Camera app)

### Please, provide the following version numbers that your issue occurs with:

- CLI: 4.0.0-2018-03-01-10793
- Cross-platform modules: 3.4.0
- Runtime(s): 3.4.1
- Plugin(s): 3.0.0-ALPHA.1

### Please, tell us how to recreate the issue in as much detail as possible. 
Here is the structure of the page (pretty simple): 
```
Page.page--camera
  StackLayout
    AdvancedVideoView(
      quality="480p"
      cameraPosition="back"
      ref="camera"
      height="40%"
    )
    Button(@tap="$modal.close()" text="Back")
```

### Is there any code involved? 
Here is the crash report when I set to `cameraPosition` to `front`:

* This is an error from the TNS console *
```
System.err: java.lang.RuntimeException: Cannot get available preview/video sizes
System.err:     at co.fitcom.fancycamera.Camera2.openCamera(Camera2.java:213)
System.err:     at co.fitcom.fancycamera.FancyCamera.onSurfaceTextureAvailable(FancyCamera.java:153)
System.err:     at android.view.TextureView.getHardwareLayer(TextureView.java:390)
System.err:     at android.view.TextureView.draw(TextureView.java:339)
System.err:     at android.view.View.updateDisplayListIfDirty(View.java:16167)
System.err:     at android.view.View.draw(View.java:16951)
System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
System.err:     at android.view.View.updateDisplayListIfDirty(View.java:16162)
System.err:     at android.view.View.draw(View.java:16951)
System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
System.err:     at android.view.View.draw(View.java:17188)
System.err:     at android.view.View.updateDisplayListIfDirty(View.java:16167)
System.err:     at android.view.View.draw(View.java:16951)
System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
System.err:     at android.view.View.updateDisplayListIfDirty(View.java:16162)
System.err:     at android.view.View.draw(View.java:16951)
System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
System.err:     at android.view.View.updateDisplayListIfDirty(View.java:16162)
System.err:     at android.view.View.draw(View.java:16951)
System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
System.err:     at android.view.View.draw(View.java:17188)
System.err:     at com.android.internal.policy.DecorView.draw(DecorView.java:753)
System.err:     at android.view.View.updateDisplayListIfDirty(View.java:16167)
System.err:     at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)
System.err:     at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:654)
System.err:     at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:762)
System.err:     at android.view.ViewRootImpl.draw(ViewRootImpl.java:2800)
System.err:     at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2608)
System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2215)
System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:686)
System.err:     at android.view.Choreographer.doFrame(Choreographer.java:621)
System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
System.err:     at android.os.Handler.handleCallback(Handler.java:751)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     at android.os.Looper.loop(Looper.java:154)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6119)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

---
Here is the error appearing within the simulator when I set `cameraPosition` to `back`
```
An uncaught Exception occurred on "CameraThread" thread.
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
    at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6891)
    at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:1083)
    at android.view.ViewGroup.invalidateChild(ViewGroup.java:5205)
    at android.view.View.invalidateInternal(View.java:13656)
    at android.view.View.invalidate(View.java:13620)
    at android.view.View.invalidateParentIfNeeded(View.java:13809)
    at android.view.TextureView.setTransform(TextureView.java:486)
    at co.fitcom.fancycamera.Camera2.configureTransform(Camera2.java:548)
    at co.fitcom.fancycamera.Camera2.access$100(Camera2.java:51)
    at co.fitcom.fancycamera.Camera2$1.onOpened(Camera2.java:224)
    at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:134)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by Tronix117** [comment]
Ok, I removed everything, remove platform, re-add plugin, re-add platform, now I can't build anymore:

```
Running full build
.../platforms/android/app/src/main/java/com/tns/gen/co/fitcom/fancycamera/CameraEventListenerUI_fbundle_l62041_c68__.java:3: error: CameraEventListenerUI_fbun
dle_l62041_c68__ is not abstract and does not override abstract method onPhotoEventUI(PhotoEvent) in CameraEventListenerUI
public class CameraEventListenerUI_fbundle_l62041_c68__ extends co.fitcom.fancycamera.CameraEventListenerUI implements com.tns.NativeScriptHashCodeProvider {
       ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
```

**Comment by triniwiz** [comment]
That’s new I’ll look into it
