### ISSUE TITLE
AdvancedVideoView crashes App on start

### ISSUE THREAD

**Issue by FariJan** [triniwiz/nativescript-videorecorder#78]
On start my app crashes with following Error-Log:
```An uncaught Exception occurred on "main" thread.
Calling js method onCreateView failed
Error: java.lang.IllegalStateException: CameraX is not initialized properly. Either CameraX.initialize() needs to have been called or the CameraXConfig.Provider interface must be implemented by your Application class.

StackTrace:
AdvancedVideoView.createNativeView(file:` node_modules\nativescript-videorecorder\advanced\advanced-video-view.android.js:47:15)
	at ViewBase._setupUI(file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:511:30)
	at (file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:553:18)
	at LayoutBaseCommon.eachChildView(file: node_modules\@nativescript\core\ui\layouts\layout-base-common.js:125:25)
	at ViewCommon.eachChild(file: node_modules\@nativescript\core\ui\core\view\view-common.js:925:13)
	at ViewBase._setupUI(file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:552:13)
	at (file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:553:18)
	at ContentView.eachChildView(file: node_modules\@nativescript\core\ui\content-view\content-view.js:70:12)
	at PageBase.eachChildView(file: node_modules\@nativescript\core\ui\page\page-common.js:126:39)
	at ViewCommon.eachChild(file: node_modules\@nativescript\core\ui\core\view\view-common.js:925:13)
	at ViewBase._setupUI(file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:552:13)
	at ViewBase._addViewCore(file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:448:17)
	at ViewBase._addView(file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:437:13)
	at FragmentCallbacksImplementation.onCreateView(file: node_modules\@nativescript\core\ui\frame\frame.android.js:700:18)
	at FragmentClass.onCreateView(file: node_modules\@nativescript\core\ui\frame\fragment.android.js:29:37)
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
	at com.tns.Runtime.callJSMethod(Runtime.java:1160)
	at com.tns.Runtime.callJSMethod(Runtime.java:1138)
	at com.tns.Runtime.callJSMethod(Runtime.java:1134)
	at com.tns.FragmentClass.onCreateView(FragmentClass.java:53)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2439)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
	at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7811)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
Caused by: java.lang.IllegalStateException: CameraX is not initialized properly. Either CameraX.initialize() needs to have been called or the CameraXConfig.Provider interface must be implemented by your Application class.
	at androidx.camera.core.CameraX.getOrCreateInstance(CameraX.java:797)
	at androidx.camera.lifecycle.ProcessCameraProvider.getInstance(ProcessCameraProvider.java:98)
	at co.fitcom.fancycamera.FancyCamera.init(FancyCamera.kt:214)
	at co.fitcom.fancycamera.FancyCamera.<init>(FancyCamera.kt:159)
    System.err: 	... 24 more
```

Found this on Stackoverflow [https://stackoverflow.com/a/59376041/10947127](url) but have no idea how to use this or if it could help.

### Which platform(s) does my issue occur on?
- Android
- Android 10
- device, Samsung Galaxy S9+

### Version numbers that my issue occurs with:

- CLI: 6.5.0
- Cross-platform modules: 6.5.1
- Runtime(s): 6.5.0
- Plugin(s): 
```
  "dependencies": {
    "@teammaestro/nativescript-svg": "^1.0.1",
    "nativescript-ui-listview": "^8.1.1",
    "nativescript-videoplayer": "^4.2.1",
    "nativescript-videorecorder": "^3.0.0-beta.6",
    "nativescript-vue": "^2.5.1",
    "tns-core-modules": "^6.5.1",
    "vue-class-component": "^6.3.2",
    "vue-property-decorator": "^7.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "@babel/preset-env": "^7.9.0",
    "babel-loader": "^8.1.0",
    "nativescript-dev-webpack": "^1.5.1",
    "nativescript-vue-template-compiler": "^2.5.1",
    "nativescript-worker-loader": "~0.9.0",
    "node-sass": "^4.13.1",
    "tns-platform-declarations": "^6.5.1",
    "typescript": "^3.8.3",
    "vue": "^2.6.11",
    "vue-loader": "^15.9.1"
  }
```

### how to recreate the issue in as much detail as possible. 

- Create NativeScript-Vue App
- Open App with AdvancedVideoView

### Is there any code involved? 
**main.ts**
```Typescript
import Vue from 'nativescript-vue';

Vue.registerElement('AdvancedVideoView', () => require('nativescript-videorecorder/advanced').AdvancedVideoView);

new Vue({
  
  render: h => h('frame', [h(App)])
}).$start();
```

**App.vue**
```Typescript
<template>
    <Page>
        <StackLayout orientation="horizontal">
            <AdvancedVideoView
                ref="cameraView"
                height="700"
                width="300"
                quality="MAX_1080p"
                cameraPosition="back"
                fill="true"/>
        </StackLayout>
    </Page>
</template>

<script lang="ts">
    import Vue from "nativescript-vue";
    import { Component } from "vue-property-decorator";
    @Component({})
    export default class App extends Vue {
    }
</script>

<style lang="scss">
</style>
```

**Comment by ElieSol** [comment]
Hello FariJan did you find a solution to this ? Have the same issue here (working with Nativescript-Vue + Typescript) and didn't manage to fix it with the stackoverflow solutions ^^

**Comment by FariJan** [comment]
I used the fork Videorecorder X
https://market.nativescript.org/plugins/nativescript-videorecorder-x
No problem with this

**Comment by ElieSol** [comment]
Great I will try this, thank you @FariJan :)

**Comment by ElieSol** [comment]
Hi again @FariJan , may I ask if you are able (and how) using Nativescript Vue+ Typescript to call the method .startRecording() in the App script ?

**Comment by FariJan** [comment]
@ElieSol yes
```<template>
...
<AdvancedVideoView
                ref="cameraView" ...

...

<script lang="ts">
    //...//
    import NativeViewElement from "@/interfaces/NativeViewElement";
    import {AdvancedVideoView} from "nativescript-videorecorder-x/advanced";
    //...//
@Component
    export default class RecordVideo extends Vue {
        videoRecorder:AdvancedVideoView;
        onLoaded(){
           this.videoRecorder = (<NativeViewElement>this.$refs['cameraView']).nativeView as AdvancedVideoView;
       //...//
           this.videoRecorder.startRecording();
```

**Comment by ElieSol** [comment]
@FariJan  Thank you very much !! This helps a lot :)
